apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-config

data:

  prometheus.yml: |
  {{ .Files.Get "monitoring/prometheus.yml" | indent 4 }}

  alerts.yml: |
  {{ .Files.Get "monitoring/alerts.yml" | indent 4 }}