apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: redis
  namespace: development

spec:
  serviceName: redis

  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis

          image: redis:7-alpine

          ports:
            - containerPort: 6379

          command:
            - redis-server

          args:
            - --appendonly
            - "yes"

          volumeMounts:
            - name: redis-data
              mountPath: /data

          resources:
            requests:
              cpu: 25m
              memory: 32Mi

            limits:
              cpu: 100m
              memory: 128Mi

  volumeClaimTemplates:
    - metadata:
        name: redis-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 2Gi