---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: identity-service-secret
  namespace: development
spec:
  encryptedData:
    JWT_SECRET: AgCPAX3Mn1u0zFutgSisUHn31HsqJzeAuRwREwgDGoKAoRB6zf14He5x9AMySNq+9snrkN7xqtj0IglbK8nj5OWxnZ/zeLf/bt+1vybE/I8vT8SXccxcmwgQq6XQzJkWf3rVYGunQbObJPFDTSeAMEB3TYueAMfLob2Kp6dPpQBxyzV4oHgGpHLOs+RmxDxJvWd/cmCeMW2guYdxFb9NM8eVMBu8UV/+mijaBVCIH/uupEutNGCdk7tq0z90g6iZcHU6zt3/oA+5d3uOGxzKPdiRRJEKBUihuf2JMWzQVDhmPSjvDxcp76K8KbIyCr4I38XMDd+nazl0n2aXVzwE0YlYrV3z6fxH6nT6y9RizL1Z+AusG/UaXBNK/fj12RG9+aq4wNKh+bJ4ywWsq2GIksD0ieItFfBCzHeugc+137t2ho9pO5hey8ANaxnZp+imYNIujqQBiaORIUQaHQ6amVktiq4gRJKwaTnzQYyLMSl7cqjZKAV0wzL16nUTnJ65qKhAcKzv1h1p3RysyrIsp9C3cxuwmB7VAmfmED+ayNytpCr/sqmxIVIPAB9Nt22w1WCIPO2/fxmOUix86hGuQn+z0br4t8J3i5xDnJJ0jQjDOVmJojmLTPIoxiWT7lSM62G0cka0i1gC4BrjQXTeKBsHRhnxpkF3+l9gcdwSHMIsnjAxuhqAYVBtrjlz/YrM91f6R0tS5kWY6r5W
    MONGODB_URI: AgBWiSuAGBaZvzCDktPZlsSOizYNiWJKpHP+JqD6QLFXRJXZXz4Vzo9w9HGDEN5rH6eNgQzRuzYWuudfwqybRoCSJO91rBuKTJ5sSBAAfAKDTOdXPm+3kKH8ijy+vdMRDw1sLql0Vnu0IgfStviYv6wBDdoWrGifnt+Fdlw6NDVZyRYtdIqR9HBm9kWi1sJ6yWppb08h2rJ5Kqge1FnQH0iwfHarRW0VtfpBaP1zqV0TED7RiuTL6iTP+Dhimz/6C+UwqI9FEiZBGnJ+OjyUnYLYdjyWe0/UjjM/FsAaKB/9LVojCMOottVmRnAPmBkW9p45cpayoAsogEYmkhg6AQyKS/WQmkLv9tp8MCr3qBndommN68QTReV9K5Zjw70H2bHODRq4cb9K73THlItZUpMU8/lzeZ9mm6lU+cBk0zezmNmM8Mw5wEvN3qBJbI2yeOF8BzgfqJNgC75MaLT9OiMB1KqU4A2K/MtTrugyY+e/3pSyLMIUyKZKUSqcX0TTVnZP+4v4FTxzM6FgbNh8Hir6CzCiSQ3MeRA0RZZuLSmL63h5D+3nrslFC+ztbGv9/7+YetYTLhhzW9Vfd7T2tXs+amwKOmpZcjf8buLsy3947Adoqvj4iG0NqF2NUYDMjF8PxwBhuo4DeHPl14vGm/uumMSYYv6ueIsXmFCcprQ5isY99yahbkNqAbGjT8TLN99VzpPDfAu0cvOMiKgnLCpbsU6ejj3HkK0Jx0YRSI2z4sMtkRth4pkZTvIm4fUt3Tyx2w==
  template:
    metadata:
      name: identity-service-secret
      namespace: development
    type: Opaque
