---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: identity-service-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    JWT_SECRET: AgDPMcAlvPI4r5541fpOyiX1YIk/89wPlAbugB24ReRc9T8TkerUizdjZQ4RgLJn5zeHpe9Z59tDNoZMc8+BQlTAIigF4KtZAOFwBagzGMvvdbQRP4NLz/JN7CopSGs5aTL0l8aGWi6vBkx3YWgjPdjTwUSf7/cMacLZaAQICqxKv9Kktph08D+OLJGqon7pfF3D+FbFPfk2OIyeOoZDnM3ICBpq5xZ0vpHFC0qBWKJSWvKGtLb5osAp9slrxsB+7cuPMJbtPRnVb8e9pGo/dvFTsZOMikxf+fQD6JutPVw5EC0qIVinwfboMVBv5Lh4pL7h0DTJ4gkYFNMtVyT70458PocC7c0BesX6aI7mnS8mNmz1IS8sPTry3BGq5rw6Iap8xOnIcIYq1Dvby5vXlScRH4cMqZFDSd9QpJhSzbxxQ5yj0tij8Yok3376dlvYJ7RdfPKHqpEJ9KBeyxNrY6xh5czI15dx6pQW3eCgV89QKBxFzl+0NgBEcDQEiFsnRhumpS0ZS1yhtYopMaXA6nX8Ilgxa+/qhA/BHl8D/btGU2OsWrkw4e0u8o5o3bD+1TZwujLesz0cVdoggnNH7xqTiOQFySHfOCIdyQKaVmUpd5F5WIgGlIQOkj+eCaIjkahFl11wDlrtcyaRWbz6GceAZxEPsi2eJFL0+NstRfalHHx8VkPoWJaPS2p49gZHvkQwRCE/+fq1pAui
    MONGODB_URI: AgCjRWdy5siM9uxyIUjcmI456euArxiNpkOSrZyXe2Q0Bnv4Z6PA6TovmLN5Fg+bpY3aFHhsqsv7t2CkKgK3Bzi577BabyKmhJ9GpB7aRZE5lltGgw/4eJf26HVRyutLoD3rL20UEBZcaoIiFA8EQEny2kSHTQxQTvvfAb1eJZ3fCgna5AvYjBt/3uLn7wZEya02PCSWF1FdC39HdopxaDzQcesVzAP8WD3X/QU9c65w8lkLS9PP3yDt6i3lpqrKuMRI0TSA0xiaTQ2FIvoBHCQuP8XJ/AJYi/nB3/+m2XdeQucYAFzipBsR8kwirHXepq4O/jb6IBoYD8ZDk+uhFDvtCj+J/B/xrwKaj/GvlePdi8syJhTxsrdrlq96/KAPrFjB5XLLFKY7MrrA9BPh1+yJ5THpACdKe5hIfKhXO8ngRPXo4y7Bs+IZ30rSZLNDe8EY8d2jmwRHRPxhV/eeBAW9x+5ssHHi5W2TDxluNFjIqmwX4/Dp9y78owmpq/dderYvuq0fvwFQOGJsTmOaKpo5P/8acdzJR6kL54z6GeT0GMZRyjLWdVH7whW/Qa3AlPlWUV/PvNnDyTzp7NyN8NmRl2Ivj67/l/QN+XlFlkzfZhJbT4c9Yd/CXy4M1+ZLW+nQb6Nddu2isf8RN3XZA7BQPQ+CgDG+mpOyuqbtnWTUHQ6/Iikx0EDGrGPNtlHm7aAhgIyFx2jVkvGyqnYpCe0sGwIDepKhScvnMFLYVO5Vlk/zKhivruk+B7x1koXpCJ4wDw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: identity-service-secret
    type: Opaque
