---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: identity-service-secret
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgCebQ9clKUTifLnd4TCPFDO4O2xSRNIfCC8CKYSq28kIPv1jaP2z2AhsUyp/yRUcYFhH1VIrfJGqN32TVrf53lNYcuPsKt90NjNjdr8qO0sLevNrLtOXjsgYzAE4ZxIeJZhrM1vT2H1vAgBf/6gPPIVyQXnp9N/Uf+vi1ySQh0guQOXc5hTY7iQb9zESu/3JUmly+f1dACUFMGpdPoBCNR/+2HCyZbR/bPoLtodHp8jym0K4koeCziYO6Jlty5m6Azw9A8TkyDqwg2kuFFPBJi/mwzauQiw5RDHT3jXjIg70BO4CZq5irlzEUTLySz/Dm464yaLmXmsIzc6Dkz903ZXFXwbinKrtzSKO1hPMLGfOFuudfS5t0ZpSLWAWLlQuhhVc13r/rdgkW4r8zvTl8x1EBIClajMwhUJLE3XEYFbnYmcr0E+mKFlnGZnWsdnWInMON0u4hKMMhlvOsng3kD9BKMDlJyckCRAXmJsn2yapmudbCRRUnpshW7mRBXB0r5v8V5WettHWU2/61wjBSyhhUIKGrFuOWhzYVk5uPfOcbYqCBtbnYywF+xcZg0z6m+54RNllvl4MJbX8hmGl5QHUmg2T9V5UCfE2dvMQrT3arc17UVO1Y+Fx4lFB4yrFnFQPxeANJpTNc4D2kntcK2n5iKw4geRKDSC0d9biWEui6f6Z6SLpD4HBpLHzKnvC39NK+zWTtYktEzb
    MONGODB_URI: AgA38rJmq0+x9YrHD2aIcSjWmSdFqgiE8vX9fnbPdyax9ag2GVsrecBxnz0H/bPEWSpMzzm6UmBfEK0bN7sn99lakq6WUuKuvqApM8Bll9h4RLjoJyqAZWEGW+zYe4xX1JW/rOViEagah+2BWinQzz7zldCYJS3DSf4lGQzSwyhvFBpYBaImMXSCVIs65VcwlAFNrSUQIkOehYyQ6Ks+Ce1xCUFbFiIbcuBKKA7PKCZ9NP5ON55jfOp3NH6mkXZ0IqpzTp8dE6ZtHN+Cjq710Z+6XYaBVamng88d9DzyXyWlDLXgle8+Vm2Y5QVccgIbEH+7n03SzTDOM9W0EajIeWC8yqZaY7uo1AgSpVK1zUseRrRP0YJQo8PSHhr/3mqwdj9TfyLu3rDBSk1Heot9IclcBkObQYAsK3J/ecBqgW++FrlTfJWs60pNGLS2r6Gl1aHuyBVf2yoJepbQV0o9wddrr7uNGt7EijF2VRdNY3/AmMhFmnQhZ4uNXG6jPvCXEFfdQrQR6Lqq4Qf7b5EMLhhQ8fMImQos3Xaa+lHnKopOfodPeZk9UoaIFm68kd621MPnBtB4Kc9wWK8wG5r+TkxG1/edzSavmB3c/qmMWiAzBBhUO9rzn29YmmyfQV07Sbtvz7SQP3YGpFXzzGdC6sRCkjezndsfM+qieGPfuo3VshEvu+epek/4azHTgYcht2bU60b67UeZir9NTnEsibA9VFNltxOxfxOFJelVsv/k7E67otAjpGKH8ozHUFl3l9bXew==
  template:
    metadata:
      name: identity-service-secret
      namespace: default
    type: Opaque
