apiVersion: v1

kind: Service

metadata:
  name: identity-service
  #namespace: {{ .Values.namespace }}

spec:
  selector:
    app: identity-service

  ports:
    - port: 3000
      targetPort: 3000

  type: ClusterIP