apiVersion: apps/v1
kind: Deployment

metadata:
  name: jaeger
  #namespace: {{ include "nodejs-microservices.namespace" . }}

spec:
  replicas: {{ .Values.jaeger.replicas }}

  selector:
    matchLabels:
      app: jaeger

  template:
    metadata:
      labels:
        app: jaeger

    spec:
      containers:
        - name: jaeger

          image: {{ .Values.jaeger.image }}

          imagePullPolicy: {{ .Values.jaeger.imagePullPolicy }}

          ports:
            - containerPort: 16686
            - containerPort: 4317

          resources:
          {{- toYaml .Values.jaeger.resources | nindent 12 }}