---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: post-service-secret
  namespace: development
spec:
  encryptedData:
    JWT_SECRET: AgAKXZtg1QFzsGw+K0FE/y/4UoPBHzKKEYswuxP/1xjwk5dO+/LHwx9IJ8DyjC3xFgGRtpITVJofJ+oZik6hFkSJf2YoPlLNrAHw5TgiPTOA3SxjjS9GqRu1Snmo0hjSF8d2Dlk/m3m2DHCgX/DZp2uVxxS9Rnt8IJbuwR45zSD9Cxn/pA5+T4kIodfuJ778bxNSN0BPCvItsFCOdZnIvXMInyhS0kc2GsgxeMRQ3T1hccZx5edsuZgsw0aeb6504DUNlLK53mdilaNPVTguQFLv3xrpKtZC+coVEAn4N6UCgZOvMwXT9NSiMPvZVd5Yunnxr/6F7Rjzs10St5KNY0iFCoTTbE2bsu5WcRAdEGbiT7JFuLY/T3iiEqk1QXSzlVp21BkrqyWNdQQsHlPvGBdv2NNc/IMOHq1uAYTfzAd6TeWv0+DI59HSmsMEwvA6kOw3ZoYDLjhuKgyyVV6kxnnEw3u3TBBljXq/Pw7iXia0oJe9X6BPAsmqqPb/p9Nzheg4DjBDiAs3VZmtY5to6f9kFF3kbq367s+Gtsc3BLTRvCDX8Na4x8LHC9UKLXkRD34J8M/CwMjpLkEhmGnE93CB75OrpuMEhv/34bB8WjnnHfdy+ZMrNURZsdb3dI7tLmeXJFdt/yp3Rax9kG1nHcRJdGo9L7vACfElwkxJ04xeMdOupHmJi0i0MeIbAQ9G8NJvdJTBOM0pNWnY
    MONGODB_URI: AgCoI/RNJ5me6Fd3wTTsZ+aEfFd7AjGKTmG10Cke25+FKIQZ30dCnBT/fAtud6/M3PKmBJf7dNACSKEmgQTcI/lbAZipMeYXH03AEU3VuvLlcYwN6d6UcXdeU+HtdE0YkBD4MODmvNa8NOpTjbdoP5qdPJiArRBQEo44fWTGw4rC0x1f37NiHSN/oQBgA4gjI5DoAMwCOE1F5IVgyras2d+bxOdxUviDpLbXABZVz9P1s7MDCGwazDzhhHQiyjApNZK3NKV3IPfdlI3UYsv9ZAHorcslQgA6/D0qB3PmR5Wc139Isnb1zkz+UiAQg8KXsyAcBSoM73XKrMVYGH6XtJi/ktg/5I8pMvXP5LgizHEkBXqbkMJf3pXmKy6foMPnLCjry9fHxCUWwTo2g3IPd82qD3O3n+aO5GbYqS5O4z9237FDtu2PwyBhZkG0LjjAmdIxpQQ/TeJ6IcyS7tOIIYizO34mxDRMhG0SwuH6V/1BuPs+gu+OQaGKaKVyTCprm78r/ayU8sSZM00/ODGrEH2zLUw80YZjncKFnFngG4bPaulIi+W8ZqmFFy+bpTqj1hZ/Y/WLTWmJyvREKjboEPlVeq7oywt5DVbSFHJGBIns65JzwqRUTuMh6SxJ4V0yDWnodi0ddO0waQfKKHxURj6x1oL9hzwBU/L4n7Kw6zKVKK7hJfutoao0VC5jX6B0ZC7LIyBTsVFjtSY6yqFesPBehOr3S7R1D1EfUS/2ST0UJN2ZG1Lc2qmnL1yjE8SD
  template:
    metadata:
      name: post-service-secret
      namespace: development
    type: Opaque
