---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: post-service-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    JWT_SECRET: AgCyiN8hq6+uhiRXnLtYpDpigkOLpqe6XNQbsabUxTO7+5FZSlUXWdt1vuNHcS+KA4+DcUq9jIZ73rjUqMxzjmpFJXhJfwlKNz3qjklkzPf0ni3053GrffdL+08Z7ZmPWakIw8m6Ge3EL9egJegi0Qez6uNrA00jmzf1owhuVc4FdhtopZGpSzslP/Sm0ewSY6tECcRyJW1j1xAnTqjy5eu/XCTMkkT9/c6Ox6c/phAVy8AaXo9Mm3BSzIhTBOvvBPd2yLeiA2I40ainmhs2bmqBISkqb9uvAHQR1m5kE/MoE8RydSPewB4iFyDJYLVTJKYQYrGUN0aXsY9wln6aJrGijNtLRP0dB+RoOFIWmvCQhgBCjYKrA1mXbJNGSD+dy/S0Gq95UqawvA5RyD5KGFXih+Y+KKTLcFhA2bZwLM7NIdWZ7WG/zb2qjRlAVKhKdhqyfUbBSuNSpdyc00wdWcMNui1/QSXgc1JVaSy+4DScpbaql1faUzqWmSit2ZtdVKk0C9u2+nQaqCswYJdh75xPQslSvsaT695neLSd94PBrTCJ3qyJxmT9JSNWCQr7VKk10TWM90ATOMdmRgFESkfN8Sg51z+kcT7JzwpkeChkxJVHdyjlagxqFdGjsMEMXAnWY7Gp1k7N7e6DVGg9ot9EFzdyg1RPsvjXk2HdXX4JtAgTyoto7+a+3Kl1YdEkpY8ZL+jqMbUh203c
    MONGODB_URI: AgB/EvvheRLpjQHrJBkpE6K2D3PUc64gExHoZRmRrXGGk1a/Dmb5cB9H6mqtBthq14YgFCf4Re5ZKlhfvxdYcFZhwqDMWm8BxaW+/TVRWKZ/zscmF3fY6SJSb0mGdj1wXP1rrctJ+Z11ER0Nw34CzhPRJ6WjoGy4O+9jGfW+5sMT+KU8YuJh8GG0JtbWeVK4bY/U13D3AySqCdmi6Pru1LnoTSC3I/04vNpOSrg9rsT2xj/4bqqzpl69mXkQaLLQT/0hDUAr38tGWyye5CAuO7wFl5t+1BPpLl3h6s2hBBz9tFjZ8MmzucgjKvNytzOT5p3o7FZwi3YUbKP3DcgclW24JquXHf9PdQltZTQDDksyiYC2Er5Gk1LUbapy1tPERrivG8YH3Uj4TVeG7aNLWpY/GI3VXn3hENkuy2djcsLU2PzTpKP17F43BMSvhvs4S3+yWwHTY/dGyJldbsVKAfhgQXnLqnHWPfTxPgY03FssrsvxZpswzboS0oIR/0l9S7aInQ1NtrCsSrbTgRWTCvsDmsjk8rO3pwtFX6yUzJs7fEffpDbKFSoAsm5uD3r8hFFq9PKuR85kt4GOurJlw9Nw6ZW4a9vIkeZZ1mUausqclCHnulwJx6AzL5/fPSg4F/VWOqhDT1cIvbMJGC4HWVmhAnu3yRbmn2fu8cAEYCjl09/HGtBmOmr+mv7TiZSzb68rlOAcOzcEvqrhCU3IY7OoL9ZJE71JlQHtlim6/xrYZ27CX7eqMMiJJy8rptvi
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: post-service-secret
    type: Opaque
