---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: post-service-secret
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgB6rYDFmu89kiZRKECZbRxYL3NTmuCq6dfcDXXdYVrHu2I1rY9r+nF79gtkmFfnwhQh2zADeOEiVK7+M6TjQNYdZgwM5Z6tlDbOxtx3UYTpdAkpGnQinTa6lM2U6p44WsFlzpLaNdBea4suVDgeMBj717+espAdreISqTxm17CxcYmRlL4vTKn+vsmc/jAOl59fabYys3If8EDnBU4hrMbpwtLLn/DvvMVyS0hcfO514h+OZKVkuAmpPMpiF4NO5ZeRBK6vrNOEAS0PhfLn/UebwA0uYhDzr+Vgkg7pAYPS6QvpzvwTKFtqP0CzvKJZBbuFa8wE6tC32Vmd33kO/zw0EjwU01wJz9yBh4SdHPnThggUA21pnGeWdx8nMnz9e+OAEUjnBchjr60DWmSFmoPgfDgKkNFVAp1Md7b40qFV/pwO6a62H4iRnevauedt5WLB0BPluX/bl9X5YzuvIav4mrk7l9xzCcjLtitKONcGYl17EkVlivQmfD/mOAVtHgNxvzePes7JmN0uoT7I8/qdT1dVG0GpX6Yn2RHMx1Kd/Qe61WlKiEEAQimCv3xqYdwpGlX4ZsJh7gIXumZ/2G/d5o4kK45N3s7pWG11fnGNq/qZXwOcMzXgU/p36h2QBAfDZe8I7xFFYYwiAbCG38NOKDZjLZQzuLcATeoPbgznaggm5m7Ollzs1I5fVsM5hkQOOz/6e/gPss+U
    MONGODB_URI: AgBOGm0lxC3IKTAIy9f9udHojnfTP+XbudLmYRQU5+V82omIriwo0R2nuW2J1DFDmtovZzlimb5evU/CEt0HIG4e4ztj8gm81P9GKgpHDSW5kX9Az2DRyP4lvZi2VEjqEuyi0HrAGzdKsAsJQWEdKzCrzu6NB7Qxzih4qGWPj3DU2VevV4N9WdMwiwWcykHm3oFGvzpIukS++DlIoC25FnbGSIJ641QGJhn3CHYm5XMU4aPKsatfIKfZ+6Pyp0eYWDPuZ4nnOnqjSSViwxBNCOpvNqIE5rSzDFuZumD1lhNYpv8YQ0zmDAVjuDQg2t0nDvhaSkDLWEc9XldtDb7VjONZaBJS8xeK8jR3IaoG4e5OmnfUXlMHCtJN5cEKrhA/aacffywi4CxUImYs1OGrZAG5ZVfKY2B0NJ6vg0Ec3cRe/j3nfgEmfcgW+H4YGX4Cgq7UWmhAZpaZrRi/zHfpAKwlUZsJ69qVQQeVJOW73T2fbnEy5jqeocDRNa1oFrVtHbm/ZjeBUUsIGjWky22hmm9+GBxQWahaBx0lyYv/pX/CgkCEHs2iPwO+9svR68Jzn3+8GNEMmto1/HYNs2iUx40g4F8xZicfyvObFtdRYSVui9Wc1WJZhAIhhSP/HjA/bb5t6gf4hHNjJDejXkY3TZAuf1B8XjHVYY0TYuGNjm+15SRyltFrjSM0rjA/BsYjbMnsXJPQApaJl1Nb20fd5r6fAcG5bBSZopvYD7gWmLDX3gyca+en/NhlSgLFxGRZ
  template:
    metadata:
      name: post-service-secret
      namespace: default
    type: Opaque
