apiVersion: v1
kind: Service

metadata:
  name: post-service
  #namespace: {{ include "nodejs-microservices.namespace" . }}

spec:
  selector:
    app: post-service

  ports:
    - port: 3000
      targetPort: 3000

  type: ClusterIP