apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: alertmanager-data

spec:

  accessModes:
    - ReadWriteOnce

  resources:

    requests:

      storage: {{ .Values.alertmanager.storage.size }}