apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: development

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          #image: ghcr.io/kippytech/api-gateway:latest  #${IMAGE_TAG}
          image: nodejs-microservices-2025-api-gateway:latest

          imagePullPolicy: Never  #IfNotPresent

          envFrom:
            - configMapRef:
                name: api-gateway-config

            - secretRef:
                name: api-gateway-secret

          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"

          startupProbe:
            httpGet:
              path: /api/health
              port: 3000

            failureThreshold: 30
            periodSeconds: 2

          readinessProbe:
            httpGet:
              path: /api/ready
              port: 3000

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000

            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3