---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: search-service-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    JWT_SECRET: AgC/cjnh6eoU8k9T95OKiGUzb/WuHBB+XFIZSt7rrNy+S9wB7bK/ceNkFpr4+2Bx1zbGh3gGnHAnntVOaVy6mADKaDIkW9tJRXj6VR0w3FHx4XNTXE2kwsz7rbVguP1PX4gp+ZACQbEqzX+PC5rbHnT4dGlbCRXWKmozt//UkOpqiqegZ6Z1Q1pYoRIyTRf2fxlvQLl+PGf17W4gA/M+PeHU5cVXGIO8CcoaqatfJZhzmuKtS9nnk0DHFLSw9Oe9L22lz37tH/yjxxxNooLS4UF5VV7VjnQzQZl+/RH2u6bdQaangHAvHMuL9yK3XNuPDSi/rcX+es5UVvFRp4C1SrIgUHIycRCsJGfZ7fxr34eaypD/Ydabcu0HJCxuGiAs6jB+HpJQha8gXgg0spTC3mbz9KBUDRxkfZzFml128lf5U8SEtnnOY3qnPlvsLLSzHINptdJ1ct6kIM11P2l/4rYt+Qziy/mB38ryz1nSBV0PtKgVs0h/Z3CamRU0PZGd8FR/rL87MFmx2lV/AaH3UliXjtawo9FNH4dmA/5RIcEbz6qt34Sq1WXPbVoj4uXSmt4JkkyerJH7d+GdRMiCmKELYnSxtHRnN1le9PRh1coqJxmeFogmrK9Ud/r+8U/47zVzXqedN9pkrL6rFaWhWdFqTLeqmXOQ3hnzUYeGLutAjvZe8CnVA7Dy3C3fKtTYFPwJvTDwdcLmFOMO
    MONGODB_URI: AgBg1AFN7i3/xnJA1YN80hSgEtwKMgbxbxL5a7Kt+ZeitG9xDsVYRlh3Au8qnbSrWfAWwhpNME7eA8uLduGf7eGHVKnYI7Vi/bYRPaaF4tWs74BPxkeuogRVbyyojdeHhF3VcepaAwCB5oXeFbGpYGpMp2ZGbb4OPwXO5UjZLs92g3Rm5MZrMkbeFjBOW+98nejt0PVxzoloyxjrF6GU95yr1jb0hnZ2GQpwEzXtDaMtQ1gvYs3O86ykrsrNLINE1ehqBLia4s0d4lUo2D5KjIiFFjO0qSyAqIZJg9yTCP8SIdkplR6Hn+ACCb+vzQJVYWM9pJB3Yx96mOWkOGFeTQnwsnCGvm67JgDSw5Z79+6eaOhXFls4B884XoxAorYoW87LMnCf9lrHJFaejf4xNiE7fYLU2lrhmD+e/qJJcLAMPOIE6wSkM+MlkArjgVj5j5rizEcLBNaIHtpyN/mzSRH4uGz0pslc9EK6iCkF90jBrt4gBLJk0plcgi54d7A45JQdsU/YwX6ukQDhGOCDKjG17pKd6qQ3J/vVdfiLbYHe1Xju1naUYB9Pn7zuMnJJfD8QqKQos/VPZSnQUQamXacwG08KasSuYQyMrAzp2TCzuT1F6rzmfeNm0eZgmtjd82CYpeEwORabcWLQ+5w9mK96HTqiZdg4otxHuzOzZ4gDhZInukTE8ZBCOF5SXG6gdSZmUSmKf+uqqB/G+iWBTqwCrL4UKUu33nwYtUM22rbpy2qsX73NqJS9f3538n6T03M=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: search-service-secret
    type: Opaque
