---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: search-service-secret
  namespace: development
spec:
  encryptedData:
    JWT_SECRET: AgBQnUAes3ReqVLbEOZ1cf3SUJ9fBjGSUdGnLSe3lM1ivKLVsqxitwz+06KSIjLQDVn8IWkd/BNbwwMsUURv36618Br8KiR0COno8D1hliOL6FmuF+VJFVKyMi67GHuv5IKETV7ziwpRUCgOzDmoorftHHv37MLpry/7rwNjoltKNhQMWxtRzXcEZHDtFI5Dp/uQMk6zoTwzdW8IwQtpy5thI1J3NCoFGgIl/WmLo7cdrJfRB9H2QPh8M4CGfxjiWfkVQO3fa86Ii5OCcV73NguCAV9XC2J6EWRaLTXNJqalYsicACZDck/n2sNd9iOlLUrSW41RAWcYuMhaqwg6rVEt1fHVVlZNLYOMPhHJ/7yKsyuMI3WHzs2Gl5AzrOaSJVIERYsvxnvhqn4QXgFTqeaOhSHm8SkaH9w0EmxXppLqfImftak7vGXJuFehtPHW8hJR+HpxC3caF0GrEX+vol9cgMUfuZY9L++lBrq8d7WZtUp202/8/Gs8rl7hsrFqSpuCvNiAumdxDYx9pwqr3slR7pxSjaMu70/+kT2en6Vs1DQn10qSP/+xm2YNCbfwDTiOCdKPhR+MK6syQS2+Vl4Rv0LYguxYoFGI/W1heCpt70llvuj5WQedHNTOv+0BbA75O7Tf+6owatowv4cOeKMaqiqIt0IaM8mjsaAbioRvr44S0jLrH07sT/kYL4P64mUxY2njupUE7dVD
    MONGODB_URI: AgCBnEzRBJVnv6OPgWKg314fHoQd+eYj6sTeBHyKGgAI5fEWmTfytqUr4RaQPedqGOORL+mBvKJfU7bs+POILikPb1lrqsnVIoajrZR7elqi2u6xo46HyfnhMpsO9YUmSiAjnpllHQaX4mzmxjUHDJFtef/OMca8pI7gB2Nb6XbsbA/sgTCCdF13xnyDqnoVSuqj83xzJ1fiupX8H17BNAyCTkiNh5IH5JQfPaVJ0KG96FyFzS5Do0NJLVgGlKAEOz3KyJ3tcE7kQpBeEyBS+IB3E7RkPavy/DUnfZAgZPiwBILAaVjeRCYeHx9TYXxCTHwjSFeGTfMd1jlPvmUv+mHKfDwZZ2B46CK+ciYUj+JnTpTWuUwuli+Hqicurkdnrn9DHlHw0ALDp5D2BplDoiFbmbXnn9gi3vLZuX9rC7Jq9uajDz4Ulm765r2zhQcrVe0sh41yXfP52doJOPoweREzWeC1yKU/rN1k9VbNVgUpv3qMCEAO2RE7PzxbWgYylaL4SDVPRy5mcRdIc8mwawrHPJQJhzMBHWLfZAVRYblDLhhjoWKAAMpC1gj0gS49zfIoQLmeOZtfoeB2L2uSATJ2JEXGslRhqEKSUkrt+yy29IuJ/U/2/s238thwelFemzZ42CqW4zBdd//aI/X5eShLZdOCeYHDFNzRuxJRpCDwdt/+pgJVFA/C3lYRblDg6uAg96Tnf01LwU3uvQQb23xk5fetbPTRpZ2d7vNmOIK5TIrqBh8L/6S56pheas/tDfE=
  template:
    metadata:
      name: search-service-secret
      namespace: development
    type: Opaque
