---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: search-service-secret
  namespace: development
spec:
  encryptedData:
    JWT_SECRET: AgBsZ/5PgCZza6mPaaP4mbIsNZZ73qFNDV0GsBKLL3vIesYwWL3awMXBjYqKiutioNmYLgRybacPJuRQiKrDkgZP21qiEHwepqaqXoyKjZtxZKxFd9G5gM7MRhfhCKpRHO8+ECpSeP/For29g1ZkTgFsPok+bo9SRGn+4QLx6K0LsCTTfZm6baMxdcftZOsKBCNuxvoES84Z7iEwXFOFx+ABiC3xwi7pZjRPJtqaereyHXv2yXXz4B9EGRJRMdm7vazgpCPs6unbI5trWJAh4TWp8eUxRvEnOJz1ij7YvCiMyhaTomNKgTE8xiBL7b8WB+IClKp51UMDQO2v44TwVVBfnmExOea54g8/JVPzCTQRnCIYqHKz9hR29kM+3kAsw8E/mgafkdWu5ltZb0goLugLwQFlQ/eeUBKbV/3oXRcC8zJ0MEv2ZwUl8jxzXfp+YATJaztcOMU4mXuUT7byrioTb+3ywQvb+bEvj3oUcxAGpTU+354uX5iaO4Ov+J5rK5Wp9vA/W8fkRjECtU36mohczoJrHh/xOra/6y46sozFF4ISHfkGQA5n8sk0e0sLAtaaEqZZIpkonZ5F0jtIhx0kr6q8UdErysLKgf9qJ2bbVX/SBbEsx+aym16OchVniiec5z5mNjT3J13lQdAbEnYShfexA9JhQRlBSGXY90p2vLFoZtzJh6Ho7xk9ywKNGzNZZO7sPMQueS4O
    MONGODB_URI: AgBfM9VXWZMUx1YeG61gcBiEfFLr3LBdOXFlyOor8hwkHtwJzgn+mbkNl40sdKsB8dUD3pOOUmnxdm35Ty+O9/Rt5CRLr5T3suKEueAmlRbg4d1XF3HOZKZzm6PMc1zTrHzXum/4KIn+OV20WcDp8rUNwO2+mLw3p3LrK3L7MNz+GTbT7wJMLyJHA9ZkaSylMuuFkxb4wVqDyRxoFj/gVexP8WatPByrp7aWAoR7q6STQ3F4On+CBY6VIMrpaIXDPkBL9bCtgNQwwtgeQTfiVi4PGUNihhDhkC2PLe6p3pGAPUxZR04xmHxYQ95RITWFY7pvayBUk5R+VhndFd+BX+LVfNzTZHKiHYEU5srcC/Vcoz5hDDHDVTn+iF+NMWWl3JMOZGYM8dl8rSudjNN23S2YW8bsF3kKCDWLSvKdpjEsrEURI6jwdih7yDwOYmVaml6N+nYdfOYHqxFyMw8OeSCSv5lkERueldHBIe2TrXgWVhurMqq5uOEO418mw58K6MjlCMkvD8V69Co/kROFksJtZdTMV1lmcNwIORhTA8q8oDUz7YwWxPfZqcWWjvrrayhwuU/jfZnOosu8Q2an4HtyN4A4ywHFPVDzqAbIEzsCpRP76SFCCQNddrwDifOxMKlkZtl6qWCv8d4zH97z6LvH9lSXGF+PN184MS01PXCH6qVaAQo7J6aKN/cHTkV0e94pwTaiHxpLgAh1LwjXWAISrH/K6GtLSjIFE7yU9S8tX0g9qF2zHbl44zVpAcL+aFM=
  template:
    metadata:
      name: search-service-secret
      namespace: development
    type: Opaque
