apiVersion: v1
kind: Secret

metadata:
  name: media-service-secret
  namespace: development

type: Opaque

stringData:
  MONGODB_URI: mongodb://mongodb:27017/media-db?replicaSet=rs0

  cloud_name: zq4kvhfh

  api_key: "612867384543569"

  api_secret: Gvmiwf8B4h0N-Ws_jlLaiuyR3Oc