apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nodejs-microservices
  namespace: argocd

spec:
  project: default

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

  source:
    repoURL: https://github.com/kippytech/nodejs-microservices.git
    targetRevision: HEAD
    path: helm/nodejs-microservices

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true