apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: nodejs-microservices
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: hard

spec:
  goTemplate: true

  goTemplateOptions:
    - missingkey=error

  generators:
    - list:
        elements:

          - environment: dev
            namespace: development
            valuesFile: values-dev.yaml

            # template:
            #   spec:
            #     syncPolicy:
            #       automated:
            #         prune: true
            #         selfHeal: true

          - environment: staging
            namespace: staging
            valuesFile: values-staging.yaml

          #   template:
          #     spec:
          #       syncPolicy: {}

          - environment: prod
            namespace: production
            valuesFile: values-prod.yaml

          #   template:
          #     spec:
          #       syncPolicy: {}

  template:

    metadata:
      name: "nodejs-microservices-{{ .environment}}"

      annotations:
        notifications.argoproj.io/subscribe.discord-sync-succeeded.discord: ""
        notifications.argoproj.io/subscribe.discord-sync-failed.discord: ""

    spec:

      #project: default
      project: nodejs-microservices

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas

      source:
        repoURL: https://github.com/kippytech/nodejs-microservices.git
        targetRevision: main
        path: helm/nodejs-microservices

        helm:
          valueFiles:
            - values.yaml
            - "{{ .valuesFile}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace}}"

      syncPolicy:
        syncOptions:
          - CreateNamespace=true

  templatePatch: |
    spec:
      {{- if eq .environment "dev" }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      {{- end }}