apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: nodejs-microservices-cloud-lab
  namespace: argocd

spec:
  goTemplate: true

  goTemplateOptions:
    - missingkey=error

  generators:
    - list:
        elements:
          - environment: dev
            namespace: development
            valuesFile: values-dev.yaml

  template:
    metadata:
      name: "nodejs-microservices-cloud-{{ .environment }}"

    spec:
      project: nodejs-microservices

      source:
        repoURL: https://github.com/kippytech/nodejs-microservices.git
        targetRevision: main
        path: helm/nodejs-microservices

        helm:
          valueFiles:
            - values.yaml
            - "{{ .valuesFile }}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas