apiVersion: v1
kind: Secret

metadata:
  name: search-service-secret
  namespace: development

type: Opaque

stringData:
  JWT_SECRET: JWT_SECRET

  MONGODB_URI: mongodb://mongodb:27017/search-db?replicaSet=rs0