apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  #namespace: {{ include "nodejs-microservices.namespace" . }}

spec:
  replicas: {{ .Values.apiGateway.replicas }}

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          #image: ghcr.io/kippytech/api-gateway:latest  #${IMAGE_TAG}
          #image: nodejs-microservices-2025-api-gateway:latest
          #image: {{ index .Values.images "api-gateway" }}
          image: "{{ index .Values.images "api-gateway" }}:{{ .Values.image.tag }}"

          #imagePullPolicy: Never  #IfNotPresent
          imagePullPolicy: {{ .Values.imagePullPolicy.local }}

          envFrom:
            - configMapRef:
                name: {{ .Values.apiGateway.configMap }}

            - secretRef:
                name: {{ .Values.apiGateway.secret }}

          ports:
            - containerPort: 3000

          resources:
          {{- toYaml .Values.resources | nindent 12 }}

          startupProbe:
            httpGet:
              path: /api/health
              port: 3000

            failureThreshold: 30
            periodSeconds: 2

          readinessProbe:
            httpGet:
              path: /api/ready
              port: 3000

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000

            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3