---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-gateway-secret
  namespace: development
spec:
  encryptedData:
    JWT_SECRET: AgBP/xczQOBU9SLV9DuA/6yJ60ysW3zEulKVXnyOBQHImM4DYDG377K5DdboBDoMZlf4lQsIjx8eCUBA411pMFFsNk+hIHQP08jTJTD7tIx1R3n07n71Knf7KPxvVXZ0nDz+zcEOpidU4qZzqIcufSu0bH48RLxEUMVgS+Qd7xx2/67S9pcfVBaSTK1RDLWWYZTd/+bI0YrJx9knd8ThPAw999AcnLCnGLI+sgpQHACfcV/2FjgP7CPGNX4j5q3zKGqMwklAEB1R/MnadbeGsDs/+Sl7JP5EtVrAXD1jHIzM4BE9BI9SL0Vk9ABWZkccespEPtmYLlxYHterwarjnngqtrr2v8NKbM6xCOYvBCvRISyesWq/vjiPszGnaZKgg+5vWuMFm2AlDjUzqMBM6/RHQZsdpm/dOOJeMPClhfhKVZuAW7i0+MQADhoLkXzO0TugXBGWqnrxE5EaVhoi+I8VyoVQIbxufarCb2dFf39ucHnz849jn0kFNeIi3S638vTBiFnhyzInxYR2k5qkbsAdG0CyIfMBwaoEwIcig/QBO/5mOyCN7dLbhaHtLo+gx0IQ5gnRRYGjBVgR1up5LVe+/cL23Jx/j4ff46VbLtXH0P0DuutYz37tPoK9W/AyAHapdRWXnS6WcFEH0s7d69AgpgsXSdgGH3oufoY2KHapcN3rcUbfTWzPTrksCaTlKTmyyby2T6S+uJIy
  template:
    metadata:
      name: api-gateway-secret
      namespace: development
    type: Opaque
