---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-gateway-secret
  namespace: development
spec:
  encryptedData:
    JWT_SECRET: AgAZBOM9ik5opYviK3B3ijLnTdhxSspo1qZGoxfaevxP7EwQg0ZY1MpbKDtfXqlLj7ITSM7j7fbW4NYHihMlpaLGJf99d9FUOs/XdqWpuISb1ZmbyGMYfmC+nrSY6fvWj5CM5KVhmpGWZ0olvOb67s+WAEv/a4RNM6BXKQFWe++8Fu9WX31WGctWfNYFJzTitzCCzD0EEtUSPa3jbvUJnb9eKEDgWVawi3wi9ygCB0mziDYfNE67n2YaLTHC+ZJhuOBXVKbnnXEPwvmrkZCPOMXtz22cvpGind8kDl6t7r+wY9nISDdIcebLeZvKT51BzRIk/NOjqPOgxaViA+4dco75DB2E/szY8bJrntM2ngc9DVGLU12st69mp0XxWoBlWmH/1aOtClaWjy8bWS6fFOLmwT09f6IjIE8CL37ORtJpX4K7w8oOarIWqQjIAq5E/ehXxfjUaDqIZ2WMcqPbTATmZlYYgANIDXmobpi4I6/UEmSFDMPX0it9jfd+JSqgchOMMbxs5g85ubUSKXUM1cdIZbB7w6Z7ESUMi6yoRKG55jZoDBVOsgkEKKOlyKKh1O4gvxoVeBD63AR2wKqkMe5oMVVJDc64gK3SGUBiwQwQN+EFSMD+iSOwQAS2kI3FCPYLOHDxm4rvf6pvZ3G7pBiKuW+ZHU2XISkeJrUTpdSQfWrd7IFI4vVyc7Ls/gwTwX68Ak/JHojPgwaI
  template:
    metadata:
      name: api-gateway-secret
      namespace: development
    type: Opaque
