---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-gateway-secret
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgBvUZHKdEYjYbOex/WZ+87tmj1Q/qxMaoYt8jWHb2jfponUoaggQmEj+l9ZE6NDM1/MotliWHyo3L6o5tWn0GjzlRBdVbbfoXXjNx9cGw+iRPb/P+FJzCWKXJkSgcTMP7m6sa3UZ5vG6+OJIN8D2En9o7oL+XVXvIejv8Os+TnwtIN0VFAmIjGH2hxTuzuk3KtPfrvnPglJCOXwmBwzyOLOKc00tegQQks6vApgcPRq2bbFS8axxyP756tzYU/QtHL8r6ZqFBZUMsET9/eArhMwMKGop2sZ6cH2QFwZ5QZXykbE1eeWNE3zjQbTn8Q2XOarETQqh5ECkAH0ddsNIxwpiwPuj1QzqbiuEY3xslmjZLshVQn6h9NPcP99a1WIJPhej1NwWI20FoxT7YduS1MI9xPHIQP8Rlp3Vr/NNE/TNv7CvQnhE15VYORAG6yfObKg1e5ZY4P+douRDfgvwi6/j0N+8X7brr4mQCtAUvYi4Jv/d7FwE7OkWclDv2rGgy5rWP4Xzua8JPc8yH5cfFl2Ue8jCDqHDaNyk0hFQIv+hCAR9/5OqfLqTw1jLuf+YYeFj2kBZLbZcGz6OpT4lsIEBqiMANblSpv0F+jZ5Di+k32eOyTf1Aehuq6CN2j2/9jRWbrVhSvhWMTqB6mNSrcvz54xV9uT4jYMek/79B8z4fSqVGA3QqdXbYyigeJ8FZmGvT3slURzUIzD
  template:
    metadata:
      name: api-gateway-secret
      namespace: default
    type: Opaque
