apiVersion: v1
kind: Secret

metadata:
  name: identity-service-secret
  namespace: development

type: Opaque

stringData:
  JWT_SECRET: JWT_SECRET

  MONGODB_URI: mongodb://mongodb:27017/identity-db?replicaSet=rs0