apiVersion: apps/v1
kind: Deployment

metadata:
  name: media-service
  #namespace: {{ include "nodejs-microservices.namespace" . }}

spec:
  replicas: {{ .Values.mediaService.replicas }}

  selector:
    matchLabels:
      app: media-service

  template:
    metadata:
      labels:
        app: media-service

    spec:
      containers:
        - name: media-service

          image: {{ index .Values.images "media-service" }}

          imagePullPolicy: {{ .Values.imagePullPolicy.local }}

          envFrom:
            - configMapRef:
                name: {{ .Values.mediaService.configMap }}

            - secretRef:
                name: {{ .Values.mediaService.secret }}

          ports:
            - containerPort: 3000

          resources:
          {{- toYaml .Values.resources | nindent 12 }}

          startupProbe:
            httpGet:
              path: /api/health
              port: 3000

            failureThreshold: 30
            periodSeconds: 2

          readinessProbe:
            httpGet:
              path: /api/ready
              port: 3000

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000

            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3