image:
  tag: ade22bb89218206e40b75d95bd96f293738a8808

# Small local environment
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 256Mi

ingress:
  className: alb