image:
  tag: 8c6a6ac28d419d7fda5ec4b733f4e61051b5f48d

# Small local environment
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 256Mi

ingress:
  className: alb