image:
  tag: 79e2e556936e41d2de5c565f03c840fa0df90deb

# Small local environment
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 256Mi

ingress:
  className: alb